let staticData = [
    {
        title: "ŠTA JE COVID 19 ?",
        date: "5.4.2020",
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut tortor elit. Morbi orci sapien, eleifend non condimentum et, interdum vel nunc. Sed quis enim pellentesque, eleifend metus a, consectetur massa. Fusce venenatis dolor vitae purus malesuada, vitae pulvinar metus pulvinar. Aliquam erat volutpat. Proin tempus non mi id dictum. Duis ac augue fermentum, pellentesque erat et, mattis urna. Integer hendrerit leo velit, quis placerat sapien mollis posuere. Mauris interdum leo sed hendrerit sodales. Nullam ligula nisl, fringilla vel est vitae, egestas pellentesque elit. Aliquam dignissim id sem vitae malesuada. Suspendisse iaculis odio at tortor maximus suscipit nec ut mi. Nam eget pharetra diam. Praesent fringilla ullamcorper ipsum, nec cursus enim sodales eget. Vivamus et bibendum ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Maecenas vel ex ac tortor accumsan facilisis ac id metus. Vestibulum ullamcorper malesuada malesuada. Nunc lobortis, nunc volutpat eleifend sagittis, nunc diam scelerisque quam, sed auctor leo lacus fermentum enim. Donec vitae libero a massa venenatis commodo. Etiam nibh nunc, luctus quis facilisis ut, dapibus eu lacus. Phasellus pharetra sollicitudin tempor. Sed elementum lectus libero, in finibus eros malesuada a. Suspendisse turpis arcu, efficitur eu nunc et, volutpat cursus ligula. Maecenas pharetra molestie sapien vitae fermentum. Donec fermentum pharetra nunc, vitae condimentum elit facilisis a. Vivamus blandit rutrum ante, sed efficitur leo sagittis quis. Mauris viverra sit amet augue sed lobortis. Quisque porttitor, leo et ultricies tincidunt, neque nulla laoreet enim, et facilisis diam ante eget arcu. Vestibulum lacinia dolor justo, at porttitor elit suscipit vitae. Sed eu consectetur elit.

Mauris nec sagittis massa. Pellentesque fringilla, dui et viverra gravida, massa arcu pellentesque sapien, et tincidunt sem libero non libero. Suspendisse sit amet elit et turpis ultrices rhoncus. Sed consequat quis sapien ac tincidunt. Quisque iaculis arcu ut pretium pharetra. Fusce finibus imperdiet lectus vitae faucibus. Morbi varius urna ac lectus faucibus tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dapibus sagittis metus ut facilisis. Nunc luctus elit sit amet tellus vulputate pellentesque. Donec dictum ante sem, et aliquam dolor feugiat eu. Phasellus viverra nibh ligula, ut tempor felis ultricies nec. Nulla mauris neque, accumsan sit amet enim ut, placerat convallis est. Proin dignissim finibus magna, malesuada condimentum tortor vulputate eu. Pellentesque vel aliquam ligula. Cras risus leo, pretium nec viverra a, consequat finibus nisi.

Vestibulum mattis ipsum sit amet congue placerat. Quisque et massa posuere, congue turpis eget, pharetra ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu dictum nisl, id ultrices diam. Curabitur ac nisi et ligula aliquet finibus. Mauris in quam quis ligula malesuada aliquam. Nam quis ante et nulla vulputate gravida. Nulla pharetra ante vitae accumsan consectetur. Vestibulum facilisis finibus tortor, eget tempus diam semper a. Suspendisse ultricies, leo quis viverra malesuada, erat sapien pulvinar magna, id mattis neque turpis vitae orci. Aliquam quis ultrices urna. Proin dapibus, nibh id rutrum placerat, dolor mauris sodales nibh, eleifend dapibus felis nisl ac dui. Phasellus at odio ultricies, porta dolor molestie, finibus est. Aenean auctor aliquam ornare. Curabitur sit amet nunc eget nunc iaculis viverra.

Sed at ullamcorper dolor. Quisque volutpat, ligula ac viverra volutpat, quam leo placerat orci, quis mollis urna turpis nec est. Nam dictum nisl id quam pulvinar dignissim. Suspendisse ac augue scelerisque, pulvinar lectus a, maximus purus. Maecenas molestie metus risus, sed tincidunt risus sagittis ut. Aenean sed arcu egestas, laoreet purus sit amet, ornare ipsum. Phasellus non suscipit sem. Aenean porttitor eu est eu consequat. Duis ullamcorper aliquet mauris, quis congue risus posuere sit amet. Cras imperdiet ullamcorper metus, eu consequat ligula eleifend vitae. Sed non massa massa. Pellentesque eu tempus neque. Quisque blandit leo nec dolor blandit commodo. Cras malesuada nibh quis ipsum iaculis interdum. Integer dapibus ex eget mi dictum, eget imperdiet velit interdum.`
    },
    {
        title: "COVID 19 TESTIRANJE",
        date: "5.4.2020",
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut tortor elit. Morbi orci sapien, eleifend non condimentum et, interdum vel nunc. Sed quis enim pellentesque, eleifend metus a, consectetur massa. Fusce venenatis dolor vitae purus malesuada, vitae pulvinar metus pulvinar. Aliquam erat volutpat. Proin tempus non mi id dictum. Duis ac augue fermentum, pellentesque erat et, mattis urna. Integer hendrerit leo velit, quis placerat sapien mollis posuere. Mauris interdum leo sed hendrerit sodales. Nullam ligula nisl, fringilla vel est vitae, egestas pellentesque elit. Aliquam dignissim id sem vitae malesuada. Suspendisse iaculis odio at tortor maximus suscipit nec ut mi. Nam eget pharetra diam. Praesent fringilla ullamcorper ipsum, nec cursus enim sodales eget. Vivamus et bibendum ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Maecenas vel ex ac tortor accumsan facilisis ac id metus. Vestibulum ullamcorper malesuada malesuada. Nunc lobortis, nunc volutpat eleifend sagittis, nunc diam scelerisque quam, sed auctor leo lacus fermentum enim. Donec vitae libero a massa venenatis commodo. Etiam nibh nunc, luctus quis facilisis ut, dapibus eu lacus. Phasellus pharetra sollicitudin tempor. Sed elementum lectus libero, in finibus eros malesuada a. Suspendisse turpis arcu, efficitur eu nunc et, volutpat cursus ligula. Maecenas pharetra molestie sapien vitae fermentum. Donec fermentum pharetra nunc, vitae condimentum elit facilisis a. Vivamus blandit rutrum ante, sed efficitur leo sagittis quis. Mauris viverra sit amet augue sed lobortis. Quisque porttitor, leo et ultricies tincidunt, neque nulla laoreet enim, et facilisis diam ante eget arcu. Vestibulum lacinia dolor justo, at porttitor elit suscipit vitae. Sed eu consectetur elit.

Mauris nec sagittis massa. Pellentesque fringilla, dui et viverra gravida, massa arcu pellentesque sapien, et tincidunt sem libero non libero. Suspendisse sit amet elit et turpis ultrices rhoncus. Sed consequat quis sapien ac tincidunt. Quisque iaculis arcu ut pretium pharetra. Fusce finibus imperdiet lectus vitae faucibus. Morbi varius urna ac lectus faucibus tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dapibus sagittis metus ut facilisis. Nunc luctus elit sit amet tellus vulputate pellentesque. Donec dictum ante sem, et aliquam dolor feugiat eu. Phasellus viverra nibh ligula, ut tempor felis ultricies nec. Nulla mauris neque, accumsan sit amet enim ut, placerat convallis est. Proin dignissim finibus magna, malesuada condimentum tortor vulputate eu. Pellentesque vel aliquam ligula. Cras risus leo, pretium nec viverra a, consequat finibus nisi.

Vestibulum mattis ipsum sit amet congue placerat. Quisque et massa posuere, congue turpis eget, pharetra ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu dictum nisl, id ultrices diam. Curabitur ac nisi et ligula aliquet finibus. Mauris in quam quis ligula malesuada aliquam. Nam quis ante et nulla vulputate gravida. Nulla pharetra ante vitae accumsan consectetur. Vestibulum facilisis finibus tortor, eget tempus diam semper a. Suspendisse ultricies, leo quis viverra malesuada, erat sapien pulvinar magna, id mattis neque turpis vitae orci. Aliquam quis ultrices urna. Proin dapibus, nibh id rutrum placerat, dolor mauris sodales nibh, eleifend dapibus felis nisl ac dui. Phasellus at odio ultricies, porta dolor molestie, finibus est. Aenean auctor aliquam ornare. Curabitur sit amet nunc eget nunc iaculis viverra.

Sed at ullamcorper dolor. Quisque volutpat, ligula ac viverra volutpat, quam leo placerat orci, quis mollis urna turpis nec est. Nam dictum nisl id quam pulvinar dignissim. Suspendisse ac augue scelerisque, pulvinar lectus a, maximus purus. Maecenas molestie metus risus, sed tincidunt risus sagittis ut. Aenean sed arcu egestas, laoreet purus sit amet, ornare ipsum. Phasellus non suscipit sem. Aenean porttitor eu est eu consequat. Duis ullamcorper aliquet mauris, quis congue risus posuere sit amet. Cras imperdiet ullamcorper metus, eu consequat ligula eleifend vitae. Sed non massa massa. Pellentesque eu tempus neque. Quisque blandit leo nec dolor blandit commodo. Cras malesuada nibh quis ipsum iaculis interdum. Integer dapibus ex eget mi dictum, eget imperdiet velit interdum.`
    },
    {
        title: "PROCES VAKCINACIJE",
        date: "5.4.2020",
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ut tortor elit. Morbi orci sapien, eleifend non condimentum et, interdum vel nunc. Sed quis enim pellentesque, eleifend metus a, consectetur massa. Fusce venenatis dolor vitae purus malesuada, vitae pulvinar metus pulvinar. Aliquam erat volutpat. Proin tempus non mi id dictum. Duis ac augue fermentum, pellentesque erat et, mattis urna. Integer hendrerit leo velit, quis placerat sapien mollis posuere. Mauris interdum leo sed hendrerit sodales. Nullam ligula nisl, fringilla vel est vitae, egestas pellentesque elit. Aliquam dignissim id sem vitae malesuada. Suspendisse iaculis odio at tortor maximus suscipit nec ut mi. Nam eget pharetra diam. Praesent fringilla ullamcorper ipsum, nec cursus enim sodales eget. Vivamus et bibendum ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Maecenas vel ex ac tortor accumsan facilisis ac id metus. Vestibulum ullamcorper malesuada malesuada. Nunc lobortis, nunc volutpat eleifend sagittis, nunc diam scelerisque quam, sed auctor leo lacus fermentum enim. Donec vitae libero a massa venenatis commodo. Etiam nibh nunc, luctus quis facilisis ut, dapibus eu lacus. Phasellus pharetra sollicitudin tempor. Sed elementum lectus libero, in finibus eros malesuada a. Suspendisse turpis arcu, efficitur eu nunc et, volutpat cursus ligula. Maecenas pharetra molestie sapien vitae fermentum. Donec fermentum pharetra nunc, vitae condimentum elit facilisis a. Vivamus blandit rutrum ante, sed efficitur leo sagittis quis. Mauris viverra sit amet augue sed lobortis. Quisque porttitor, leo et ultricies tincidunt, neque nulla laoreet enim, et facilisis diam ante eget arcu. Vestibulum lacinia dolor justo, at porttitor elit suscipit vitae. Sed eu consectetur elit.

Mauris nec sagittis massa. Pellentesque fringilla, dui et viverra gravida, massa arcu pellentesque sapien, et tincidunt sem libero non libero. Suspendisse sit amet elit et turpis ultrices rhoncus. Sed consequat quis sapien ac tincidunt. Quisque iaculis arcu ut pretium pharetra. Fusce finibus imperdiet lectus vitae faucibus. Morbi varius urna ac lectus faucibus tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dapibus sagittis metus ut facilisis. Nunc luctus elit sit amet tellus vulputate pellentesque. Donec dictum ante sem, et aliquam dolor feugiat eu. Phasellus viverra nibh ligula, ut tempor felis ultricies nec. Nulla mauris neque, accumsan sit amet enim ut, placerat convallis est. Proin dignissim finibus magna, malesuada condimentum tortor vulputate eu. Pellentesque vel aliquam ligula. Cras risus leo, pretium nec viverra a, consequat finibus nisi.

Vestibulum mattis ipsum sit amet congue placerat. Quisque et massa posuere, congue turpis eget, pharetra ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu dictum nisl, id ultrices diam. Curabitur ac nisi et ligula aliquet finibus. Mauris in quam quis ligula malesuada aliquam. Nam quis ante et nulla vulputate gravida. Nulla pharetra ante vitae accumsan consectetur. Vestibulum facilisis finibus tortor, eget tempus diam semper a. Suspendisse ultricies, leo quis viverra malesuada, erat sapien pulvinar magna, id mattis neque turpis vitae orci. Aliquam quis ultrices urna. Proin dapibus, nibh id rutrum placerat, dolor mauris sodales nibh, eleifend dapibus felis nisl ac dui. Phasellus at odio ultricies, porta dolor molestie, finibus est. Aenean auctor aliquam ornare. Curabitur sit amet nunc eget nunc iaculis viverra.

Sed at ullamcorper dolor. Quisque volutpat, ligula ac viverra volutpat, quam leo placerat orci, quis mollis urna turpis nec est. Nam dictum nisl id quam pulvinar dignissim. Suspendisse ac augue scelerisque, pulvinar lectus a, maximus purus. Maecenas molestie metus risus, sed tincidunt risus sagittis ut. Aenean sed arcu egestas, laoreet purus sit amet, ornare ipsum. Phasellus non suscipit sem. Aenean porttitor eu est eu consequat. Duis ullamcorper aliquet mauris, quis congue risus posuere sit amet. Cras imperdiet ullamcorper metus, eu consequat ligula eleifend vitae. Sed non massa massa. Pellentesque eu tempus neque. Quisque blandit leo nec dolor blandit commodo. Cras malesuada nibh quis ipsum iaculis interdum. Integer dapibus ex eget mi dictum, eget imperdiet velit interdum.`
    }
]

module.exports = staticData